### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by erperejildo** [djade007/cloudinary_public#11] opened 2021-04-03 21:13 UTC
After installing dependencies:

<img width="288" alt="Screenshot 2021-04-03 at 20 15 10" src="https://user-images.githubusercontent.com/5629919/113491577-3ea55e00-94d2-11eb-975f-4eef85c588d6.png">

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by djade007** [comment] 2021-04-03 21:23
@erperejildo Yes, `init.dart` is not currently checked into source control.

To run the example, please copy `.init.example.dart` file to `init.dart` and update your Cloudinary credentials.

**Comment by erperejildo** [comment] 2021-04-04 08:06
Ok, imported, but I don't understand how to upload files. It says that I can use it without exposing an apiKey/secretKey, but I added the cloud name and the preset name and I still don't know what to do from there. I guess I'm missing something but I don't know anything else in the README

**Comment by djade007** [comment] 2021-04-04 08:56
The issue is most likely coming from your upload preset configuration.

Make sure it looks like this, `Unsigned` and access mode should be `public`
<img width="930" alt="Screenshot 2021-04-04 at 9 55 17 AM" src="https://user-images.githubusercontent.com/8323355/113503780-e8fd9f80-952b-11eb-8371-ccad1f29fd68.png">


More documentation is here https://cloudinary.com/documentation/upload_images#unsigned_upload

**Comment by erperejildo** [comment] 2021-04-04 16:09
> https://cloudinary.com/documentation/upload_images#unsigned_upload

Ah ok so there is no way to upload files using a signed method then. I thought we had both options

**Closed** 2021-04-04 16:22 UTC
